name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: docker.pkg.github.com/splunk/pytest-splunk-addon/pytest-splunk-addon
        # Tag for the Docker image
        tag: latest,1,1.0,1.0.0
        # Script body to compute tag name for the Docker image, has context as the main function argument
        #tag script: # optional
        # Username for Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Registry URL
        registry: docker.pkg.github.com
        # Don't skip pull requests
        include pull requests: # optional
