name: Review Misspell

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run misspell with reviewdog
      uses: reviewdog/action-misspell@v1.0.0
