name: Review FLAKE8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run flake8 on your PR - with annotations!
      uses: tayfun/flake8-your-pr@1.0.1